### ISSUE TITLE
Syntax Error:Non-ascii character

### ISSUE THREAD

**Issue by 007divyachawla** [lc/theftfuzzer#1]
Hello,

While running the python file, it is giving this error.

File "theftfuzzer.py", line 13
SyntaxError: Non-ASCII character '\xe2' in file theftfuzzer.py on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Could u just tell how to resolve the issue.

**Comment by lc** [comment]
What version of python are you using and what operating system?

**Comment by 007divyachawla** [comment]
Kali linux 2.0 and python version 3

**Comment by lc** [comment]
Hi @007divyachawla,

I just attempted to fix the issue, hopefully it works. 
Can you re-download and try again to see if it is fixed?

https://github.com/sxcurity/theftfuzzer/blob/master/theftfuzzer.py

**Comment by 007divyachawla** [comment]
sure

**Comment by lc** [comment]
Let me know if that fixed the issue.

**Comment by 007divyachawla** [comment]
Thanks bro issue is fixed, btw wats the issue

**Comment by lc** [comment]
Fixed.
